---
title: "Chapter 16 Exercise"
output: html_notebook
Name: Daniel Lee
---

Setup
```{r}
library(tidyverse)
library(DataComputing)
library(mosaic)
```


### Problem 16.1
1) 
```{r}
BabyNames %>%
  filter(sex == "M") %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  filter(grepl("[aeiou]$", name)) %>%
  arrange(desc(total)) %>%
  head(10)
```

2)
```{r}
BabyNames %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  filter(grepl(".*(jo$|joe$)", name)) %>%
  arrange(desc(total)) %>%
  head(10)
```

### Problem 16.2


### Problem 16.3
1. Each matched string will be two letters, e.g. AL, AK, AS
2. There are seven strings that match in A[LKSZRAP]. For F[LM], there are two strings that match. All add up to 61 patterns.
3. Appreviations for the US states and territories

### Problem 16.4


### Problem 16.5
```{r}
CrimeSample <-
  read.file("http://tiny.cc/dcf/Boston-Crimes-50.csv")

my_regex <-
  "\\(\\s*([+-]*[0-9]*[0-9\\.][0-9]*\\s*,\\s*([+-]*[0-9]*[0-9.][0-9]*)\\s*\\)"

Result <-
  CrimeSample %>%
  extract(Location, 
          into=c("lat", "long"), 
          regex = my_regex, 
          convert = TRUE)
```
